add/urls.py
from audioop import add
from django.urls import path, include
from .views import *

app_name = 'add'

urlpatterns = [
    path('', show_add, name = "show_add"),
    path('json/',show_json,name="show_json"),
    path('addincome/', add_income, name='add_income'),
    path('addoutcome/', add_outcome, name='add_outcome'),
    path('addnote/', add_note , name='add_note'),
    path('deletenote/<int:id>/', delete_note, name='delete_note'),
    path('add_income_flutter/', add_income_flutter , name='add_income_flutter'),
    path('add_outcome_flutter/', add_outcome_flutter , name='add_outcome_flutter'),
    path('add_note_flutter/', add_note_flutter , name='add_note_flutter'),
]

nobokek/urls.py
from django.urls import path

from nobokek.views import flutter_register, show_nobokek, show_guest, show_json, show_problem, login_user, logout_user, register, create_problem, login_flutter, logout_flutter
from statistic.views import show_statistic


app_name = 'nobokek'

urlpatterns = [
    path('', show_nobokek, name='show_nobokek'),
    path('register/', register, name='register'), #sesuaikan dengan nama fungsi yang dibuat
    path('login/', login_user, name='login'), #sesuaikan dengan nama fungsi yang dibuat
    path('login-flutter/', login_flutter, name='login_flutter'),
    path('logout-flutter/', logout_flutter, name='logout_flutter'),
    path('logout/', logout_user, name='logout'), #sesuaikan dengan nama fungsi yang dibuat
    path('guest/', show_guest, name='show_guest'), #sesuaikan dengan nama fungsi yang dibuat
    path('json/', show_json, name='show_json'), #sesuaikan dengan nama fungsi yang dibuat
    path('create_problem/', create_problem, name="create_problem"),
    path('statistic/', show_statistic, name="statistic"),
    path('flutter_register/', flutter_register, name='flutter_register'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('nobokek/', include('nobokek.urls')),
    path('add/', include('add.urls')),
    path('report/', include('report.urls')),
    path('forum/', include('forum.urls')),
    path('statistic/', include('statistic.urls')),
]

report/urls.py
from django.urls import path
from report.views import *



app_name = 'report'

urlpatterns = [
    path('', show_report, name='show_report'),
    path('target/', show_target, name='show_target'),
    path('json/', show_json_ajax, name='show_json_ajax'),
    path('add/', add_todolist_ajax , name='add_todolist_ajax'),
    path('get_username/', get_username, name='get_username'),
    path('delete/<int:id>/', delete_todolist_ajax, name='delete_todolist_ajax'),
]

statistic/urls.py
from django.urls import path
from .views import *
from add.views import show_json

app_name = 'statistic'

urlpatterns = [
    path('', show_statistic, name="show_statistic"),
    path('json/', show_json, name="show_json"),
]

statistic/models.py
from add.models import Money
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
# class Stat(models.Model):
#     user = models.ForeignKey(to=User, on_delete=models.CASCADE)
#     income = models.FloatField()
#     outcome = models.FloatField()
#     date = models.DateField()
class Stat(models.Model):
    user = Money.user
    income = Money.income
    outcome = Money.outcome
    date = Money.date

statistic/views.py
from django.shortcuts import HttpResponse, render, redirect
from django.http import HttpRequest
from django.core import serializers

from add.models import Money
from .models import *
from django.contrib.auth.decorators import login_required


@login_required(login_url='/nobokek/login/')
def show_statistic(request):
    data_user = Money.objects.filter(user=request.user)
    context = {
    'list_data' : data_user,
    }
    return render(request, "statistic.html", context)

statistic/templates/statistic.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!--Code untuk navbar-->
<style>
    *{
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        font-family: 'Poppins', sans-serif;
        
    }
    body{
      min-height: 100vh;
      background: #abd699;
      overflow-x: hidden;
    }
    header{
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 80px;
      padding: 20px 40px;
      display: flex;
      justify-content: space-between;
      align-items: center;
      z-index: 1000;
      background: #75c9b7;
      
    }
    header .logo{
      color: #ffe26a;
      font-weight: 700;
      text-decoration: none;
      font-size: 2em;
      letter-spacing: 2px;
    }
    .group{
      display: flex;
      align-items: center;
    }
    header ul{
      position: relative;
      display: flex;
      gap: 30px;
    }
    header ul li{
      list-style: none;
  
    }
    header ul li a{
      position: relative;
      text-decoration: none;
      font-size: 1em;
      padding: 6px 15px;
      color: #ffe26a;
      font-weight: 700;
    }
    header ul li button{
      position: relative;
      text-decoration: none;
      font-size: 1em;
      padding: 6px 15px;
      color: #ffe26a;
      font-weight: 700;
    }
    header ul li a:hover{
      background: #ffe26a;
      color: #abd699;
      border-radius: 20px;
    }
  
    header ul li a.logout{
      background: #d80000;
      color: #ffffff;
      border-radius: 20px;
    }
    header .search{
      position: relative;
      display: flex;
      justify-content: center;
      align-items: center;
      font-size: 1.5em;
      z-index: 10;
      cursor: pointer;
    }
    .searchBox{
      position: absolute;
      right: -100%;
      width: 100%;
      height: 100%;
      display: flex;
      background: #75c9b7;
      align-items: center;
      padding: 0 30px;
      transition: 0.5s ease-in-out;
    }
    .searchBox.active{
      right: 0;
    }
    .searchBox input{
      width: 100%;
      border: none;
      outline: none;
      height: 50px;
      font-size: 1.25em;
      color: #333;
      background: #fff;
      border-bottom: 1px solid rgba(0, 0, 0, 0.5);
    }
    .searchBtn{
      position: relative;
      left: 30px;
      top: 2.5px;
      transition: 0.5s ease-in-out;
    }
    .searchBtn.active{
        left: 0;
    }
    .closeBtn{
      opacity: 0;
      visibility: hidden;
      transition: 0.5s;
      scale: 0;
    }
    .closeBtn.active{
      opacity: 1;
      visibility: visible;
      transition: 0.5s;
      scale: 1;
    }
    .menuToggle{
      position: relative;
      display: none;
    }
    @media (max-width: 1200px){
      .searchBtn{
        left: 0;
      }
      .menuToggle{
      position: absolute;
      display: block;
      font-size: 2em;
      cursor: pointer;
      transform: translateX(30px);
      z-index: 10;
      }
      header .navigation{
        position: absolute;
        opacity: 0;
        visibility: hidden;
        left: 100%;
      }
      header.open .navigation{
        top: 80px;
        opacity: 1;
        visibility: visible;
        left: 0;
        display: flex;
        flex-direction: column;
        background: #75c9b7;
        width: 100%;
        height: calc(70vh - 80px);
        padding: 40px;
        border-top: 1px solid rgba(0, 0, 0, 0.5);
        transition: 0.5s;
      }
  
      header.open .navigation li a{
        font-size: 1.25em;
      }
      .hide{
        display: none;
    }
    }
    
    section{
      position: relative;
      width: 100%;
      height: 100vh;
      padding: 100px;
      display: flex;
      justify-content: center;
      align-items: center;
    }
    section::before{
      content: '';
      position: absolute;
      bottom: 0;
      width: 100%;
      height: 100px;
      background:#abd699;
      z-index: 1000;
    }
  
    #text{
      position: absolute;
      color: #fff;
      white-space: nowrap;
      font-size: 7.5vw;
      z-index: 9;
    }
    #btn{
      text-decoration: none;
      display: inline-block;
      padding: 8px 30px;
      border-radius: 40px;
      background: #ffe26a;
      color: #abd699;
      font-size: 1.5em;
      z-index: 9;
      transform: translateY(100px);
    }
    .section-padding{
        padding: 100px 0;
    }
    .carousel-item{
      height: 100vh;
      min-height: 300px;
    }
    .carousel-caption{
      bottom: 220px;
      z-index: 2;
    }
    .carousel-caption h5{
      font-size: 45px;
      letter-spacing: 2px;
      margin-top: 25px;
      text-transform: uppercase;
    }
    .carousel-caption p{
      width: 60%;
      margin: auto;
      font-size: 18px;
      line-height: 1.9;
    }
    .carousel-inner::before{
      content: '';
      position: absolute;
      width: 100%;
      height: 100%;
      top: 0;
      left: 0;
      background: rgba(0, 0, 0, 0.7);
      z-index: 1;
    }
    
    .w-100{
      height: 100vh;
    }
    .card{
      background: #16123f;
      color: #fff;
      vertical-align: middle;
    }
</style>

<header class="fixed-top">
    <a href="#" class="logo">NoBokek App</a>
    <div class="group">
        <ul class="navigation">
            <li><a href="{% url 'add:show_add' %}">Add</a></li>
            <li><a href="{% url 'nobokek:show_nobokek' %}">Home</a></li>
            <li><a href="{% url 'report:show_report' %}">Report User Info</a></li>
            <li><a href="{% url 'button' %}">Forum</a></li>
            <li><a href="{% url 'nobokek:create_problem' %}" class="contact-us">Contact Us</a></li>      
            <li><a href="{% url 'nobokek:logout' %}" class="logout">Logout</a></li>
        </ul>
        <div class="search">
            <span class="icon">
            <ion-icon name="search-outline" class="searchBtn"></ion-icon>
            <ion-icon name="close-outline" class="closeBtn"></ion-icon>
            </span>
        </div>
        <ion-icon name="menu-outline" class="menuToggle"></ion-icon>
    </div>
    <div class="searchBox">
        <input type="text" placeholder="Search here...">
    </div>
</header>
<!--Akhir code navbar-->

<!--Code for statistic-->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.4/Chart.bundle.min.js'></script>
<script>
    $(document).ready(function(){
        $.ajax({
            url: "{% url 'add:show_json' %}",
            type: 'GET',
            success: function(data){
                console.log(data)
                let inWeek1 = 0;
                let inWeek2 = 0;
                let inWeek3 = 0;
                let inWeek4 = 0;
                let outWeek1 = 0;
                let outWeek2 = 0;
                let outWeek3 = 0;
                let outWeek4 = 0;
                for(i of data){
                    console.log(i.fields.outcome)
                    if(0 < parseInt(i.fields.date[8]+i.fields.date[9]) && parseInt(i.fields.date[8]+i.fields.date[9]) < 8){
                        inWeek1 += i.fields.income
                        outWeek1 += i.fields.outcome
                    }
                    if(7 < parseInt(i.fields.date[8]+i.fields.date[9]) && parseInt(i.fields.date[8]+i.fields.date[9]) < 15){
                        inWeek2 += i.fields.income
                        outWeek2 += i.fields.outcome
                    }
                    if(14 < parseInt(i.fields.date[8]+i.fields.date[9]) && parseInt(i.fields.date[8]+i.fields.date[9]) < 22){
                        inWeek3 += i.fields.income
                        outWeek3 += i.fields.outcome
                    }
                    if(21 < parseInt(i.fields.date[8]+i.fields.date[9]) && parseInt(i.fields.date[8]+i.fields.date[9]) < 29){
                        inWeek4 += i.fields.income
                        outWeek4 += i.fields.outcome
                    }
                }
                var ctx = $("#chart-line")
                var myLineChart = new Chart(ctx, {
                    type: 'bar',
                    data: {
                        labels: ["Minggu-1", "Minggu-2", "Minggu-3", "Minggu-4"],
                        datasets: [{
                            data: [inWeek1, inWeek2, inWeek3, inWeek4],
                            label: "Income",
                            borderColor: "#458af7",
                            backgroundColor:'#458af7',
                            fill: false
                        }, {
                            data: [outWeek1, outWeek2, outWeek3, outWeek4],
                            label: "Outcome",
                            borderColor: "#8e5ea2",
                            fill: false,
                            backgroundColor:'#8e5ea2'
                        }]
                    },
                    options: {
                        title: {
                            display: true,
                            text: 'Your statistic per month',
                        }
                    }
                })
            },
        })
    });
</script>

<link rel="stylesheet" href="{% static 'style.css' %}" />
<div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="row" style="margin-top: 35px; margin-bottom: -75px;">
            <div class="container-fluid d-flex justify-content-center">
                <div class="col-sm-8 col-md-6">
                    <div class="card">
                        <div class="dropdown justify-content-center">
                            
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" href="#">January</a>
                                <a class="dropdown-item" href="#">February</a>
                                <a class="dropdown-item" href="#">March</a>
                                <a class="dropdown-item" href="#">April</a>
                                <a class="dropdown-item" href="#">May</a>
                                <a class="dropdown-item" href="#">June</a>
                                <a class="dropdown-item" href="#">July</a>
                                <a class="dropdown-item" href="#">August</a>
                                <a class="dropdown-item" href="#">September</a>
                                <a class="dropdown-item" href="#">October</a>
                                <a class="dropdown-item" href="#">November</a>
                                <a class="dropdown-item" href="#">Desember</a>
                            </div>
                        </div>
                        <div class="card-header" style="color: black;">Your Economic Statistic</div>
                            <div class="card-body" style="height: 430px">
                                <div class="chartjs-size-monitor" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;">
                                    <div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;">
                                        <div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div>
                                    </div>
                                    <div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;">
                                        <div style="position:absolute;width:200%;height:200%;left:0; top:0"></div>
                                    </div>
                                </div> <canvas id="chart-line" width="299" height="200" class="chartjs-render-monitor" style="display: block; width: 299px; height: 200px;"></canvas>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--end statistic code-->

<script>
  let searchBtn = document.querySelector('.searchBtn');
  let closeBtn = document.querySelector('.closeBtn');
  let searchBox = document.querySelector('.searchBox');
  let navigation = document.querySelector('.navigation');
  let menuToggle = document.querySelector('.menuToggle');
  let header = document.querySelector('header');

  searchBtn.onclick = function(){
      searchBox.classList.add('active');
      closeBtn.classList.add('active');
      searchBtn.classList.add('active');
      menuToggle.classList.add('hide');
      header.classList.remove('open');
  }
  closeBtn.onclick = function(){
      searchBox.classList.remove('active');
      closeBtn.classList.remove('active');
      searchBtn.classList.remove('active');
      menuToggle.classList.remove('hide');
  }
  menuToggle.onclick = function(){
      header.classList.toggle('open');
      searchBox.classList.remove('active');
      closeBtn.classList.remove('active');
      searchBtn.classList.remove('active');
  }
</script>
{% endblock content %}