add/urls.py
from audioop import add
from django.urls import path, include
from .views import *

app_name = 'add'

urlpatterns = [
    path('', show_add, name = "show_add"),
    path('json/',show_json,name="show_json"),
    path('addincome/', add_income, name='add_income'),
    path('addoutcome/', add_outcome, name='add_outcome'),
    path('addnote/', add_note , name='add_note'),
    path('deletenote/<int:id>/', delete_note, name='delete_note'),
    path('add_income_flutter/', add_income_flutter , name='add_income_flutter'),
    path('add_outcome_flutter/', add_outcome_flutter , name='add_outcome_flutter'),
    path('add_note_flutter/', add_note_flutter , name='add_note_flutter'),
]

nobokek/urls.py
from django.urls import path

from nobokek.views import flutter_register, show_nobokek, show_guest, show_json, show_problem, login_user, logout_user, register, create_problem, login_flutter, logout_flutter
from statistic.views import show_statistic


app_name = 'nobokek'

urlpatterns = [
    path('', show_nobokek, name='show_nobokek'),
    path('register/', register, name='register'), #sesuaikan dengan nama fungsi yang dibuat
    path('login/', login_user, name='login'), #sesuaikan dengan nama fungsi yang dibuat
    path('login-flutter/', login_flutter, name='login_flutter'),
    path('logout-flutter/', logout_flutter, name='logout_flutter'),
    path('logout/', logout_user, name='logout'), #sesuaikan dengan nama fungsi yang dibuat
    path('guest/', show_guest, name='show_guest'), #sesuaikan dengan nama fungsi yang dibuat
    path('json/', show_json, name='show_json'), #sesuaikan dengan nama fungsi yang dibuat
    path('create_problem/', create_problem, name="create_problem"),
    path('statistic/', show_statistic, name="statistic"),
    path('flutter_register/', flutter_register, name='flutter_register'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('nobokek/', include('nobokek.urls')),
    path('add/', include('add.urls')),
    path('report/', include('report.urls')),
    path('forum/', include('forum.urls')),
    path('statistic/', include('statistic.urls')),
]

report/urls.py
from django.urls import path
from report.views import *



app_name = 'report'

urlpatterns = [
    path('', show_report, name='show_report'),
    path('target/', show_target, name='show_target'),
    path('json/', show_json_ajax, name='show_json_ajax'),
    path('add/', add_todolist_ajax , name='add_todolist_ajax'),
    path('get_username/', get_username, name='get_username'),
    path('delete/<int:id>/', delete_todolist_ajax, name='delete_todolist_ajax'),
]

statistic/urls.py
from django.urls import path
from .views import *
from add.views import show_json

app_name = 'statistic'

urlpatterns = [
    path('', show_statistic, name="show_statistic"),
    path('json/', show_json, name="show_json"),
]

nobokek/models.py
from datetime import datetime
from email.policy import default
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class ContactUs(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    date = models.DateField(null=True, blank=True)
    nama = models.TextField(null=True, blank=True)
    alamat = models.TextField(null=True, blank=True)
    masalah =models.TextField(null=True, blank=True)

nobokek/forms.py
from django import forms
from nobokek.models import ContactUs

class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = [
            "nama",
            "alamat",
            "masalah"
        ]
        widgets = {
           'nama' : forms.TextInput(attrs={
            'id':'nama'
           }),
           'alamat' : forms.TextInput(attrs={
            'id':'alamat'
           }),
           'masalah' : forms.Textarea(attrs={
            'id':'masalah'
           }),
        }

nobokek/views.py
import json
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from nobokek.forms import ContactForm
from nobokek.models import ContactUs
from django.core import serializers
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User

def show_guest(request):
    return render(request, "guest.html")

@login_required(login_url='/nobokek/login/')
def show_nobokek(request):  
    return render(request, "nobokek.html")

@login_required(login_url='/nobokek/login/')
def show_problem(request):
    data_problem = ContactUs.objects.filter(user=request.user)
    form = ContactUs()
    context = {
    'list_problem' : data_problem,
    'form' : form
    }
    return render(request, "contact.html", context)

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('nobokek:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

@csrf_exempt
def login_flutter(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            login(request, user)
            # Redirect to a success page.
            return JsonResponse({
            "status": True,
            "message": "Successfully Logged In!"
            # Insert any extra data if you want to pass data to Flutter
            }, status=200)
        else:
            return JsonResponse({
            "status": False,
            "message": "Failed to Login, Account Disabled."
            }, status=401)

    else:
        return JsonResponse({
        "status": False,
        "message": "Failed to Login, check your email/password."
        }, status=401)

@csrf_exempt
def flutter_register(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        username = data['username']
        password = data['password']
        is_user_already_exist = User.objects.filter(username=username).exists();
        if not is_user_already_exist:
            user = User.objects.create_user(username=username,password=password)
            user.save()
            return JsonResponse({
                "status": True,
                "username": user.username,
            }, status=200)
        else:
            return JsonResponse({
              "status": False,
              "message": "Failed to register, username already exist."
            }, status=401)
    else:
        return JsonResponse({
            "status": "error"
        }, status=401)

@csrf_exempt
def logout_flutter(request):
    try:
        logout(request)
        return JsonResponse({
            "status": True,
            "message": "Successfully Logged out!"
        }, status=200)
    except:
        return JsonResponse({
          "status": False,
          "message": "Failed to Logout"
        }, status=401)


def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("nobokek:show_nobokek")) # membuat response
            # response.set_cookie('last_login', str(datetime.now()))
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('nobokek:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/nobokek/login/')
def show_json(request):
    problem = ContactUs.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', problem), content_type='application/json')

def create_problem(request):
    form = ContactForm()
    if request.method == 'POST':
        nama = request.POST.get('nama')
        alamat = request.POST.get('alamat')
        masalah = request.POST.get('masalah')
        date = datetime.date.today()
        user = request.user
        problem_obj = ContactUs.objects.create(nama=nama, alamat=alamat, masalah=masalah, date=date, user=user)
        result = {
            'fields':{
                'nama':problem_obj.nama,
                'alamat':problem_obj.alamat,
                'masalah':problem_obj.masalah,
                'date':problem_obj.date,
                'user':problem_obj.user.username,
            },
            'pk':problem_obj.pk
        }
        return JsonResponse(result)
    return render(request, 'contact.html', {'form': form})

def add_todolist_ajax(request):
    title = request.POST.get('title')
    description = request.POST.get('description')
    add_todolist_ajax = ContactUs(
        user = request.user,
        title = title,
        description = description,
    )
    add_todolist_ajax.save()
    return JsonResponse({"target": "new target"})

nobokek/templates/contact.html
{% extends 'base.html' %}

{% block meta %}
<title>Contact Us</title>
{% endblock meta %}

{% block content %}

<style>
    *{
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family: 'Poppins', sans-serif;
    
  }
  body{
    min-height: 100vh;
    background: #abd699;
    overflow-x: hidden;
    padding: 100px 0;
  }
  header{
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 80px;
    padding: 20px 40px;
    display: flex;
    justify-content: space-between;
    align-items: center;
    z-index: 1000;
    background: #75c9b7;
    
  }
   header .logo{
    color: #ffe26a;
    font-weight: 700;
    text-decoration: none;
    font-size: 2em;
    letter-spacing: 2px;
  }
  .group{
    display: flex;
    align-items: center;
  }
  header ul{
    position: relative;
    display: flex;
    gap: 30px;
  }
  header ul li{
    list-style: none;

  }
  header ul li a{
    position: relative;
    text-decoration: none;
    font-size: 1em;
    padding: 6px 15px;
    color: #ffe26a;
    font-weight: 700;
  }
  header ul li button{
    position: relative;
    text-decoration: none;
    font-size: 1em;
    padding: 6px 15px;
    color: #ffe26a;
    font-weight: 700;
  }
  header ul li a:hover{
    background: #ffe26a;
    color: #abd699;
    border-radius: 20px;
  }

  header ul li a.logout{
    background: #d80000;
    color: #ffffff;
    border-radius: 20px;
  }
  header .search{
    position: relative;
    display: flex;
    justify-content: center;
    align-items: center;
    font-size: 1.5em;
    z-index: 10;
    cursor: pointer;
  }
  .searchBox{
    position: absolute;
    right: -100%;
    width: 100%;
    height: 100%;
    display: flex;
    background: #75c9b7;
    align-items: center;
    padding: 0 30px;
    transition: 0.5s ease-in-out;
  }
  .searchBox.active{
    right: 0;
  }
  .searchBox input{
    width: 100%;
    border: none;
    outline: none;
    height: 50px;
    font-size: 1.25em;
    color: #333;
    background: #fff;
    border-bottom: 1px solid rgba(0, 0, 0, 0.5);
  }
  .searchBtn{
    position: relative;
    left: 30px;
    top: 2.5px;
    transition: 0.5s ease-in-out;
  }
  .searchBtn.active{
    left: 0;
  }
  .closeBtn{
    opacity: 0;
    visibility: hidden;
    transition: 0.5s;
    scale: 0;
  }
  .closeBtn.active{
    opacity: 1;
    visibility: visible;
    transition: 0.5s;
    scale: 1;
  }
  .menuToggle{
    position: relative;
    display: none;
  }
  @media (max-width: 1200px){
    .searchBtn{
      left: 0;
    }
    .menuToggle{
    position: absolute;
    display: block;
    font-size: 2em;
    cursor: pointer;
    transform: translateX(30px);
    z-index: 10;
    }
    header .navigation{
      position: absolute;
      opacity: 0;
      visibility: hidden;
      left: 100%;
    }
    header.open .navigation{
      top: 80px;
      opacity: 1;
      visibility: visible;
      left: 0;
      display: flex;
      flex-direction: column;
      background: #75c9b7;
      width: 100%;
      height: calc(70vh - 80px);
      padding: 40px;
      border-top: 1px solid rgba(0, 0, 0, 0.5);
      transition: 0.5s;
    }

    header.open .navigation li a{
      font-size: 1.25em;
    }
    .hide{
      display: none;
    }
  }
  .grid-container{
    background: #ffe26a;
  }
  </style>
<header class="fixed-top" >
    <a href="{% url 'nobokek:show_nobokek' %}" class="logo">NoBokek App</a>
    <div class="group">
      
      <ul class="navigation">
        <li><a href="{% url 'add:show_add' %}">Add</a></li>
        <li><a href="{% url 'statistic:show_statistic' %}">Statistic</a></li>
        <li><a href="{% url 'report:show_report' %}">Report User Info</a></li>
        <li><a href="{% url 'button' %}">Forum</a></li>
        <li><a href="{% url 'nobokek:create_problem' %}" class="contact-us">Contact Us</a></li>      
        <li><a href="{% url 'nobokek:logout' %}" class="logout">Logout</a></li>
      </ul>
      <div class="search">
        <span class="icon">
          <ion-icon name="search-outline" class="searchBtn"></ion-icon>
          <ion-icon name="close-outline" class="closeBtn"></ion-icon>
        </span>
      </div>
      <ion-icon name="menu-outline" class="menuToggle"></ion-icon>
    </div>
    <div class="searchBox">
      <input type="text" placeholder="Search here...">
    </div>
    
</header>

<script>
  $(document).ready(function(){
      function refresh() {
      $.get("/nobokek/json", function(data) {
        $(".grid-container").empty();
        for (i=0;i<data.length;i++){
          $(".grid-container").append(`<div class="card text-bg-primary mb-3" style="max-width: 18rem;">
          <div class="card-body">
            <h4> Name </h4>
            <p class="card-text">${data[i].fields.nama}</p>
            <h4> Email </h4>
            <p class="card-text">${data[i].fields.alamat}</p>
            <h4> Problem </h4>
            <p class="card-text">${data[i].fields.masalah}</p>
          </div>`)
        }
        });
      }
      
    $("#send").click(function(){
      $.ajax({
        url:"/nobokek/create_problem/",
        type:"POST",
        dataType: "json",
        data:{
          nama : $('#nama').val(),
          alamat : $("#alamat").val(),
          masalah : $("#masalah").val(),
          csrfmiddlewaretoken: "{{ csrf_token }}"
        },
        success: function (result) {
        alert("Okay! Your problem has been sent :)")
        refresh();
      },
      error: function(){
        alert("Error")
      }
      })})
    refresh();
  });
  </script>

<center>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

<div class="d-flex justify-content-evenly">
<div class="d-flex flex-column mb-3">
  <button type="button" class="button-33" data-bs-toggle="modal" data-bs-target="#sendProblem" data-bs-whatever="@getbootstrap">Send Your Problem Here</button>
</div>
</div>

<div class="modal fade" id="sendProblem" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Tell Us Your Problem</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form>
          <div class="mb-3">
              <label for="recipient-name" class="col-form-label">Name:</label>
              {{form.nama}}
              <!-- <input type="text" min="0" class="form-control" id="nama"> -->
          </div>
          <div class="mb-3">
            <label for="recipient-name" class="col-form-label">Email:</label>
            {{form.alamat}}
            <!-- <input type="text" min="0" class="form-control" id="alamat"> -->
        </div>
          <div class="mb-3">
              <label for="message-text" class="col-form-label">Problem:</label>
              {{form.masalah}}
              <!-- <input type="text" min="0" class="form-control" id="masalah"> -->
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="send" data-bs-dismiss="modal">Send</button>
      </div>
    </div>
  </div>
</div>


<div> 
  <p> <em> Here are your problem list :( </em> </p> 
</div>



{% comment %} Add the data below this line {% endcomment %}
 </center>
 <div class = "grid-container">
</div>

<script>
  let searchBtn = document.querySelector('.searchBtn');
  let closeBtn = document.querySelector('.closeBtn');
  let searchBox = document.querySelector('.searchBox');
  let navigation = document.querySelector('.navigation');
  let menuToggle = document.querySelector('.menuToggle');
  let header = document.querySelector('header');

  searchBtn.onclick = function(){
    searchBox.classList.add('active');
    closeBtn.classList.add('active');
    searchBtn.classList.add('active');
    menuToggle.classList.add('hide');
    header.classList.remove('open');
  }
  closeBtn.onclick = function(){
    searchBox.classList.remove('active');
    closeBtn.classList.remove('active');
    searchBtn.classList.remove('active');
    menuToggle.classList.remove('hide');
  }
  menuToggle.onclick = function(){
    header.classList.toggle('open');
    searchBox.classList.remove('active');
    closeBtn.classList.remove('active');
    searchBtn.classList.remove('active');
  }
</script>
{% endblock content %}

nobokek/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
<style>
    body{
      min-height: 100vh;
      background: #abd699;
    }
  </style>
<div class="card mx-auto text-center" style="width: 20rem;">
  <div class="card-body">
    <div class = "login">

        <h1>Login</h1>
    
        <form method="POST" action="">
            {% csrf_token %}
            <table>
                <tr>
                    <td>Username: </td>
                    <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                </tr>
                        
                <tr>
                    <td>Password: </td>
                    <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                </tr>
    
                <tr>
                    <td></td>

                </tr>
            </table>
            <button class="btn bg-primary" type="submit">Login</button>
        </form>
    
        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}     
        <div>
            <a href="{% url 'nobokek:show_guest' %}">
                <button class="btn btn-outline-success" type="button">
                    Log in as a guest
                </button>
              </a>
        </div>
        <div>
            Belum mempunyai akun? <a href="{% url 'nobokek:register' %}">Buat Akun</a>
        </div>
        
    
    </div>
  </div>
</div>

{% endblock content %}

nobokek/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %} 
<style>
  body{
    min-height: 100vh;
    background: #abd699;
  }
</style>

<div class="card mx-auto" style="width: 30rem;">
    <div class="card-body">
        <div class = "login">
    
            <h1>Formulir Registrasi</h1>  
        
                <form method="POST" >  
                    {% csrf_token %}  
                    <div class="flex flex-col gap-4">
                        {% for field in form %}
                            <div class="form-control w-full max-w-md">
                                {{ field.errors }}
                                {{ field.label_tag }}
                                {{ field }}
                                {% if field.help_text %}
                                  <div class="alert alert-light text-info-content my-2">
                                    <div class="flex flex-col">{{ field.help_text | safe }}</div>
                                  </div>
                                {% endif %}
                            </div>
                        {% endfor %}
                        <div class="text-center">
                            <button class="btn btn-primary">Daftar</button>
                        </div>
                      </div>
                </form>
        
            {% if messages %}  
                <ul>   
                    {% for message in messages %}  
                        <li>{{ message }}</li>  
                        {% endfor %}  
                </ul>   
            {% endif %}
        
        </div> 
    </div>
  </div> 

{% endblock content %}